### ISSUE TITLE
Implement a script to retrieve a list of local conference videos from Youtube

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#148]
Implement a Python script to query the Youtube API for local conference videos; The following channels contain a list of videos that can be used as a starting point

*Developer Resources*
~https://www.youtube.com/channel/UCPJftRZO3wYmXLpvfRJtPhQ~
~https://www.youtube.com/channel/UCkEx935JDB6x-x5EePlc0fA~

The following may be useful for getting setup
~https://developers.google.com/youtube/v3/quickstart/python~

*Existing Data Structure *
```
{
        "created": event['created'],
        "description": event['description']['text'],
        "event_url": event['url'],
        "photo_url": "",
        "id": event['id'],
        "name": event['name']['text'],
        "group_name": event['name']['text'],
        "member_type": 'ticket',
        "status": event['status'],
        "time": event['start']['utc']
    }
```

*Acceptance Criteria*

* The script should retrieve videos from the Youtube API
* Videos should be transformed into the standard data structure - additional fields may be required

**Comment by TheMicroGirl** [comment]
I will look at this at the weekend :)

**Comment by TheMicroGirl** [comment]
note : need to get a list of videos, per channel in the format above

**Comment by apoclyps** [comment]
@TheMicroGirl The following PR provides an example script that can be used to fetch data from the Youtube API; You will need to supply your own `DEVEOPER_KEY` for the Youtube API.

The following video explain how to generate a API key : https://www.youtube.com/watch?v=pP4zvduVAqo
