### ISSUE TITLE
Implement a script to retrieve a list of local conference videos from vimeo

### ISSUE THREAD

**Issue by TheMicroGirl** [apoclyps/my-dev-space#229]
Implement a script to consume local conference videos from video and post them to the `/video` endpoint.

The youtube video script can be used as a template: https://github.com/apoclyps/my-dev-space/blob/master/scripts/src/youtube_videos.py

Data structure required : 
```python
event = {  
   "id":video_id,
   "name":video_name,
   "created":video_created,
   "url":video_url,
   "description":video_description,
   "channel":video_channel,
   "source":video_source
}
```

*Acceptance Criteria*

* The script should retrieve videos from the Vimeo API
* Videos should be transformed into the standard data structure - additional fields may be required

*Resources*
* https://github.com/vimeo/vimeo.py#get-started-with-the-vimeo-api
* vimeo python client: https://github.com/vimeo/vimeo.py
* example script : https://github.com/apoclyps/my-dev-space/tree/master/scripts

**Comment by apoclyps** [comment]
vimeo python client: https://github.com/vimeo/vimeo.py

**Comment by apoclyps** [comment]
@kik-kik let me know if there is anything I can do to help with this issue; especially if you are having any issues getting set up locally :)

**Comment by apoclyps** [comment]
@kik-kik are you still interested in this issue now that hacktoberfest has ended?

**Comment by kik-kik** [comment]
Hey, yeah sorry. Just struggling with time.
