### ISSUE TITLE
Add a security.txt file

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#261]
Create a `security.txt` file for muxer using https://securitytxt.org/

We may need to host this separate on S3 and configure a route within the Application load balancer to point towards it - if we find that the client is not a suitable place to host this file.

*Acceptance Criteria*
* Adds a `security.txt` file
* Configures nginx and docker-compose-dev.yml to provide routing to this file

**Comment by Warlord77** [comment]
@apoclyps  I can pick up this issue but to complete it you need to provide me with the things required to create a security.txt as mentioned here https://securitytxt.org/.
Encryption, Security Policy link , Signature , Acknowledgements , Contact etc

**Comment by apoclyps** [comment]
Issue to be closed as we're not currently set up to make use of it
