### ISSUE TITLE
Investigate adding travis stages to the build script

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#264]
Travis recently released [staged builds](https://blog.travis-ci.com/2018-07-18-build-stages-officially-released)

We could potentially break down the deployment process into testing/deployment/e2e; Details on how to add stages is provided [here](https://docs.travis-ci.com/user/build-stages?utm_source=blog&utm_medium=web&utm_campaign=buid_stages_ga#How-to-define-Build-Stages%3F)

At present, the `travis.yml` file links our testing, deployment, e2e scripts: https://github.com/apoclyps/my-dev-space/blob/master/.travis.yml

**Comment by Warlord77** [comment]
May I pick this up ?

**Comment by apoclyps** [comment]
@Warlord77 yes, of course. I've assigned the issue to you. It's yours 👍

**Comment by Warlord77** [comment]
I have made a pr. for this issue . Please check it
