### ISSUE TITLE
Provides Timeboxed "Slots" for meetups and aggregate how conflicted they are

### ISSUE THREAD

**Issue by andrewbolster** [apoclyps/my-dev-space#342]
**Is your feature request related to a problem? Please describe.**
"So when *can* I run this f**king meetup then?"

**Describe the solution you'd like**
API endpoint with a list of timeboxed 'windows' (i.e. date:am/date:pm, but daily could be a great initial setup) with a value for how conflicted / free that timebox is. 

Timebox declarations should be in an ISO appropriate format, where ISO dates are assumed to be fro 0000 UTC to 23:59 UTC

```json
{"slots":{
    "2018-08-29":{
        "conflicts": ["/<muxer_ref_to_conflicting_event>","..."],
    },
    "2018-08-30":{
        "conflicts": [],
    }
},
"meta":{"callbacks, pagination, success_status, etc"}
}
```

**Describe alternatives you've considered**
Could just check the site, but where's the fun in that

**Additional context**
I'll hold off on purchasing 'whencaniholdmyfuckingmeetup.com'... for a while... 😂

**Comment by apoclyps** [comment]
Resolved as part of #538
