### ISSUE TITLE
Implement a pre-commit hook for running tests

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#390]
A pre-commit hook should be added to the repository that encourages a successful test run prior to pushing a commit to the repository. The pre-commit hook should also be configurable to allow it to be manually disabled.

*Resources*

* running the test suite: https://github.com/apoclyps/my-dev-space#running-the-tests
* git hook management: https://github.com/ahmadawais/hacktoberfest#%EF%B8%8F-git-hook-management

**Comment by htalat** [comment]
hey! can i get on this?

**Comment by apoclyps** [comment]
Hi @htalat 

Thank you for the interest in this issue; You're more than welcome to pick up this issue.

**Comment by apoclyps** [comment]
Resolved by @htalat in #409
