### ISSUE TITLE
Replace depreciated Flask-Scripts with Click

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#393]
**Request**
While the `Flask-Script` maintainers are willing to merge PR's, they are not actively developing features. As of Flask 0.11, Flask includes a built-in CLI tool, and fit the projects needs better.

**Acceptance Criteria**
* `manage.py` is refactored for both `events` and `users` to use click.
* documentation is updated
* tests are updated as appropriate
* `Flask-Scripts` is removed from the Pipfile and lock file

**Additional context**
* http://flask.pocoo.org/docs/1.0/cli/#custom-commands
* https://github.com/smurfix/flask-script

**Comment by swmcc** [comment]
I want this, please Sir! :spinningswm:

**Comment by apoclyps** [comment]
Thanks @swmcc; It's all yours. I'll ping you an invite to collaborate and assign it across.
