### ISSUE TITLE
Amend Events UI to show a human readable datetime

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#394]
**Is your feature request related to a problem? Please describe.**
At present, only the humanized time to event is displayed in the UI e.g. `Next event in 3 days` however user's have requested that a date time also be provided e.g. `Thursday, 11th of October 6:00PM`

<img width="647" alt="screen shot 2018-09-30 at 14 35 04" src="https://user-images.githubusercontent.com/1443700/46258199-3f527900-c4be-11e8-90ec-09297ca42614.png">

**Describe the solution you'd like**
I would like to try an incorporate both the time to next event and the actual event time (if possible) in the events UI: https://muxer.co.uk/event .

**Describe alternatives you've considered**
Replacing the time to event with the date time

**Additional context**
* This change will need to be reflected in both upcoming events and recent events

**Comment by pmc-a** [comment]
Hey @apoclyps - I'd like to pick this one up if that's ok? 🙂

**Comment by apoclyps** [comment]
Hi @pmc-a 

Thank you for the interest in this issue; You're more than welcome to pick it up.
