### ISSUE TITLE
Implement reducer tests for `events`

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#397]
**Is your feature request related to a problem? Please describe.**
At present the reducers for the `events` redux store are untested. This issue is to add tests to cover the reducers for `events`.

**Describe the solution you'd like**
Implement tests that run as part of jest that provide coverage for the `events` reducer.

**Additional context**
* Writing tests for reducers: https://redux.js.org/recipes/writingtests#reducers
* event reducer source: https://github.com/apoclyps/my-dev-space/blob/master/services/client/src/pages/events/reducers/events.js

**Comment by Mouzourides** [comment]
I'd like to work on this :)

**Comment by apoclyps** [comment]
@Mouzourides you are more than welcome to pick up this issue; I'll send you an invitation and assign the issue to you

**Comment by apoclyps** [comment]
Closed by #418
