### ISSUE TITLE
Implement structured logging via python-json-logger for the events service

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#403]
**Is your feature request related to a problem? Please describe.**
At present the events service does not make use of logging; this ticket is to implemented structured logging via the `python-json-logger` dependency.

**Describe the solution you'd like**
* Detailed request logging by default
* Pretty exceptions in debug mode/JSON exceptions in production mode

**Additional context**
* Events service: https://github.com/apoclyps/my-dev-space/tree/master/services/events
* python-json-logger: https://github.com/madzak/python-json-logger

**Comment by cburn-r7** [comment]
Hulloo~ ! Can I take this one? :)

**Comment by RhythmOfRiora** [comment]
Hullo~! Can I take this one?

**Comment by apoclyps** [comment]
Hi @RhythmOfRiora ; You're more than welcome to pick up this issue; I've assigned the issue to you 👍

**Comment by apoclyps** [comment]
@RhythmOfRiora were you able to get set up with a local environment? let me know if there is anything I can do to help :)

**Comment by apoclyps** [comment]
@RhythmOfRiora are you still interested in this issue now that hacktoberfest has ended?
