### ISSUE TITLE
Add an Elasticsearch docker instance and an example script

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#411]
**Is your feature request related to a problem? Please describe.**
Implement Elasticsearch in the development environment using docker-compose to allow prototyping of more complex queries that could be used for searching, filtering, and supporting additional use cases.

**Describe the solution you'd like**
Implement an Elasticsearch service that will form the basis of an API that can provide more complex querying, sorting, and filtering.

**Additional context**
* A standalone example has already been prototyped here using the Muxer dataset: https://github.com/apoclyps/elasticsearch-by-example
* The major version of Elasticsearch *must* match the major version of the client: https://elasticsearch-py.readthedocs.io/en/master/

**Comment by pvsousalima** [comment]
You need a new instance connected to the already running network? Can I take it?

**Comment by apoclyps** [comment]
@warlord77 I assume @pvsousalima is still working on it. I'll keep the issue assigned for another 7 days. If there is no reply in that time, It can be reassigned otherwise it will remain assigned for the remainder of hacktoberfest.

**Comment by apoclyps** [comment]
@Warlord77 still interested in this issue?

**Comment by apoclyps** [comment]
Some initial work has been started here https://github.com/apoclyps/elasticsearch-by-example

this issue is still active
