### ISSUE TITLE
Add the `events` API to swagger documentation

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#424]
**Describe the solution you'd like**
Document the `events` endpoints within swagger

**Additional context**
* Document all events endpoints: https://github.com/apoclyps/my-dev-space/blob/master/services/events/project/api/events.py
* Add `events` API to existing `swagger.json`
* Provide a screenshot of updated swagger docs

**Comment by jomyemmanuel** [comment]
Hi, I would like to work on this.

**Comment by apoclyps** [comment]
Hi @jomyemmanuel, Thanks for the interest; you are more than welcome to pick up this issue. I will send you an invite to collaborate and I'll assign the ticket across to you.

**Comment by apoclyps** [comment]
@jomyemmanuel How were you running the local service? Was it on your machine directly or was it using docker? As far as I'm aware you shouldn't have to create a virtual environment to run the service. The only steps requiring an environment will be the `./load_data.sh` script to populate the local environment.

Also, can you tell me what output you see when you run the following:

Build and run the service locally - you should see the events-service and users-service fail but swagger and the client should both be accessible at `localhost` and `localhost/swagger`.

```
docker-compose -f docker-compose-dev.yml build service
docker-compose -f docker-compose-dev.yml up
```
Once the service starts up successfully, kill it and run the recreate_db and seed db commands. This will ensure your local database is setup correctly.
```
docker-compose -f docker-compose-dev.yml run users-service python manage.py recreate_db
docker-compose -f docker-compose-dev.yml run users-service python manage.py seed_db
docker-compose -f docker-compose-dev.yml run events-service python manage.py recreate_db
```

Lastly, run the up command and you should see everything start successfully but with no data

```
docker-compose -f docker-compose-dev.yml up
```

**Comment by apoclyps** [comment]
@jomyemmanuel a Makefile has just been merged to master. This should help in your local setup.

**Comment by jomyemmanuel** [comment]
@apoclyps Thank you so much. The Makefile seems to have fixed a lot of issues for me. In addition, `docker-compose -f docker-compose-dev.yml build` also helped.
I think `googleapiclient` needs to be added to pipfile, since it throws error `ModuleNotFoundError: No module named 'googleapiclient'`
