### ISSUE TITLE
Add the `videos` API to swagger documentation

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#425]
**Describe the solution you'd like**
Document the `videos` endpoints within swagger

**Additional context**
* Document all video endpoints: https://github.com/apoclyps/my-dev-space/blob/master/services/events/project/api/videos.py
* Add `videos` API to existing `swagger.json`
* Provide a screenshot of updated swagger docs

**Comment by momothereal** [comment]
Hi, I'll try this one out.

**Comment by apoclyps** [comment]
Hey @momothereal. Thank youfor picking up this issue you. I will send you an invite to collaborate and assign it to you

**Comment by apoclyps** [comment]
Resolved by @momothereal. Closing Issue
