### ISSUE TITLE
Implement validators for events endpoint url query parameters

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#427]
**Describe the solution you'd like**
Implement exception handling and validators for URL query parameters for the `events` view in the `events` service.

**Potential basis for a solution**

file: exceptions.py
path: app.exceptions

```python
class EventsException(Exception):
    error = "InternalServerError"
    status_code = 500
    headers = None

    def __init__(self, error=None):
        super().__init__()
        if self.error is not None:
            self.error = error

    def to_dict(self):
        return {"error": self.error}
```

file: exceptions.py
path: app.validators.exceptions

```python
from app.exceptions import EventsException

class ValidationError(EventsException):
    error = "Bad Request"
    status_code = 400    
```

file: validate_number.py
path: app.validatorss.validate_number

```python
from app.validators.exceptions import ValidationError

def validate_positive_integer(value):
    try:
        val = int(value)
    except ValueError as e:
        raise ValidationError(str(e))

    if val <= 0:
        raise ValidationError("Value '%d' is not a positive number" % val)

    return val
```

**Additional context**
* events service: https://github.com/apoclyps/my-dev-space/tree/master/services/events
* events view: https://github.com/apoclyps/my-dev-space/blob/master/services/events/project/api/events.py#L156

**Comment by htalat** [comment]
can i take this up?

**Comment by apoclyps** [comment]
@htalat of course, you're more than welcome to take it 👍

**Comment by apoclyps** [comment]
@htalat let me know if you need any help in getting your local environment set up

**Comment by htalat** [comment]
hey, sorry will get on it within this week. Will let you know if i need any help

**Comment by apoclyps** [comment]
@htalat take your time, no rush :)
