### ISSUE TITLE
Implement search bar component for events

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#440]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to filter the event results to find events contain keywords from a search.

**Describe the solution you'd like**
A search bar at the top of the page that filters result from the response stored in the `events` store.

**Describe alternatives you've considered**
Open to alternative recommendations

**Additional context**
* Example search-ui has been mocked up here but is only a suggestion; this branch can be ignored if you have an alternative idea: https://github.com/apoclyps/my-dev-space/tree/search-ui/scripts

Example: 

| No Data | With Data |
| ----- | ---- |
|<img width="1680" alt="screen shot 2018-10-07 at 10 17 46" src="https://user-images.githubusercontent.com/1443700/46580354-057ff600-ca1b-11e8-864b-a00f98c2dcab.png"> |<img width="1680" alt="screen shot 2018-10-07 at 10 22 41" src="https://user-images.githubusercontent.com/1443700/46580361-306a4a00-ca1b-11e8-989c-2e6700d5b78f.png"> |

**Comment by GustavoMantuan** [comment]
Hey, I would like to try this one!

**Comment by apoclyps** [comment]
@GustavoMantuan apologies, I forgot to assign this issue across to yourself, however, I see you got the invitation to collaborate. Are you still happy to pick up this issue?
