### ISSUE TITLE
Create a locale redux store storing the locale from the subdomain

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#472]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see events from different cities when I browse the subdomain for that city. e.g. `dublin.muxer.co.uk`. 

**Describe the solution you'd like**
Either state that is added into a redux store on load or a middleware to set the location using the subdomain. Ideally, this location will be available in a store via a selector to allow api action creators to make use of it as a parameter when requesting data from the events service.

**Additional context**
* https://www.npmjs.com/package/parse-domain could be useful
* A new locale store will need to be added

**Comment by Wgil** [comment]
Hello, I can pick this up!

Where can I find the list of available subdomains?

**Comment by apoclyps** [comment]
Of course @Wgil It's all yours.

The current list of subdomains is :
* belfast.muxer.co.uk
* glasgow
* dublin
* edinburgh

Any new solution should work with that list but remain extensible to add more cities in the future.

**Comment by apoclyps** [comment]
There is no parameter in the events API yet but I can add one. We should avoid filtering the results client side as the server can filter, gz compress, paginate, and cache the results for us helping to reduce response times. Example: `/events?city=belfast`, `?/events?city=dublin`. I've added #485 to implement it

If there are no events in a city, we should present the user with a message saying something like "Sorry, this city does not appear to have any Events." or "Please check back later or raise an issue on Github (if you think there is an error)". Feel free to change this to whatever you think provides the best user experience.

I'll also raise a ticket to provide some useful metadata in the response.

**Comment by Wgil** [comment]
.

**Comment by apoclyps** [comment]
Thank you @Wgil the changes have shipped and it's now available on https://muxer.co.uk under the following subdomains.

https://belfast.muxer.co.uk
https://dublin.muxer.co.uk
https://glasgow.muxer.co.uk
https:/edinburgh.muxer.co.uk

If you are interested in bring muxer to a city near you send me a message either here or on twitter at @apoclyps 

Closing issue as complete

**Comment by Wgil** [comment]
Hey, @apoclyps welcome! I'll definitely message you if I find some events near me :) Thank you

**Comment by Wgil** [comment]
Is it possible to bring Muxer to Caracas, Venezuela? :) What should be
taken into account?

**Comment by apoclyps** [comment]
@Wgil of course it is, there are three things needed to bring Muxer to your city.

* subdomain:
* eventbrite radius around city
* meetup id

The first is a subdomain, what is your preferred subdomain: 'caracas.muxer.co.uk', 'venezuela.muxer.co.uk', or something else?

For Eventbrite listings, how many miles radius around Caracas should events be included for? 5, 10, 25, 50, 100, etc?

For meetup events,, we need a user subscribed to as many groups as possible in that city, e.g.  my id for meetup is on my profile page in the URL: https://www.meetup.com/members/135086862/ , if you are happy to use your profile we can begin pulling in the groups and search for related events in that area.

If you can provide those details I can add the events and subdomain tomorrow :)
