### ISSUE TITLE
Add Muxer to Caracas, Venezuela

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#675]
@Wgil, there are three things needed to bring Muxer to your city.

* subdomain:
* eventbrite radius around city
* meetup id

The first is a subdomain, what is your preferred subdomain: 'caracas.muxer.co.uk', 'venezuela.muxer.co.uk', or something else?

For Eventbrite listings, how many miles radius around Caracas should events be included for? 5, 10, 25, 50, 100, etc?

For meetup events,, we need a user subscribed to as many groups as possible in that city, e.g.  my id for meetup is on my profile page in the URL: https://www.meetup.com/members/135086862/ , if you are happy to use your profile we can begin pulling in the groups and search for related events in that area.

If you can provide those details I can add the events and subdomain tomorrow :)

_Originally posted by @apoclyps in https://github.com/apoclyps/my-dev-space/issues/472#issuecomment-448770026_

**Comment by Wgil** [comment]
I would prefer to use venezuela.muxer.co.uk since currently there are not too many tech events in the country. 

I couldn't find on Eventbrite the miles radius to test. I'm not pretty sure if you can select Venezuela on Eventbrite? That would be the best scenario.

All Meetup groups linked to the account are going to appear in the listing even if they are not from here? In that case I would prefer to create a new account to only add venezuelan groups. Otherwise, I've already added some groups to my profile https://www.meetup.com/es-ES/members/199591638/

Thanks for this :)

**Comment by Wgil** [comment]
Great, I'll send you another account by Thursday,

Have a good holiday bro.

**Comment by apoclyps** [comment]
You too, Happy Holidays 🎄 🎅 🎁

**Comment by Wgil** [comment]
Here it is https://www.meetup.com/es-ES/members/218776275/ :) Hope to have active meetups in a near future

**Comment by apoclyps** [comment]
Just an update; this is still a priority on my todo list. Been a little busy running a local muxer workshop but I'll hopefully get time to tackle this in the coming days :)

**Comment by Wgil** [comment]
Take your time! :-)

**Comment by apoclyps** [comment]
Muxer subdomain has been configured for `venezuela` at https://venezuela.muxer.co.uk/

At present, only meetup.com events are loaded (there doesn't seem to be alot active at the moment). I'll work on updating the [events-pipeline](https://github.com/muxer-dev/event-pipeline) to load everything from eventbrite

**Comment by Wgil** [comment]
@apoclyps Thanks! :-) Hope to have more meetups at this side!

**Comment by apoclyps** [comment]
@Wgil I've updated the `events-pipeline` to include Eventbrite events; there are considerably more events listed on https://venezuela.muxer.co.uk/  now :) Also, we've setup a twitter over at https://twitter.com/muxer_dev ; It will contain a lot of future updates and progress updates for Muxer.

**Comment by apoclyps** [comment]
Closing issue as complete
